### ISSUE TITLE
Shift schedule interface for organizations

### ISSUE THREAD

**Issue by jmewes** [coders4help/volunteer_planner#213]
As shift manager I want to maintain a shift schedule so that it doesn't need to be maintained by an admin via email etc.
- [x] There needs to be an additional attribute for users to be declared as Manager of a particular Organization
- [x] Managers should only be able to see Facilities which belong to their organization
- [ ] Main menu entries “Shifts” and “Templates”
- [ ] Create a new task for each new shift
- [ ] i18n/l10n
- [ ] Extend demo content with multiple organizations and organization members. This would be helpful to do the demo/test/development on any computer.

**Comment by jmewes** [comment]
Feature branch on my fork: https://github.com/jmewes/volunteer_planner/tree/feature/manager_interface

**Comment by jmewes** [comment]
Google Document with notes for the development of this feature: https://docs.google.com/document/d/1N-q4AkQmI41Y66zjiETe4XmqWLHehgxZC4k6YN4QzBU/edit?usp=sharing

**Comment by jmewes** [comment]
How do we want to implement the shift deletion confirmation? I think from the user perspective it would be best to raise a JavaScript dialog. However, it won't be possible to create a PhantomJS test for it. AFAIK JavaScript dialog handling is part of that 5% PhantomJS cannot handle. The alternative would be a dedicated page with a confirmation message and ok/cancel buttons.

**Comment by christophmeissner** [comment]
How about modal views with bootstrap?

**Comment by christophmeissner** [comment]
Updated original comment with TODO list from linked google docs to keep stuff together

**Comment by christophmeissner** [comment]
duplicate ticket. please also see #204

**Comment by yeonwoon** [comment]
just pushed (very) initial changes for adding/editing shifts to my repo. with this change, now you can add/edit shift (and task) from the new shift form.
[see the change (diff)](https://github.com/yeonwoon/volunteer_planner/commit/b84ceabbec68350d8f744c6192c05329e9110273)

However, I am not entire sure how the models need to be handled (or how the new form would look like). From the perspective of code, I presumed that *creating new shift* means creating new `Shift` model instance and `Task` model instance as well in case it's unknown yet (or pick existing one), also associating these `Shift` and `Task` instances with a certain `Facility`. Does this make sense and correct?

It would be really grateful if you took a look at the commit above. or even you can grab my [feature/manager_interface branch](https://github.com/yeonwoon/volunteer_planner/commits/feature/manager_interface) to try out. Just login and new menu item called 'Shift' will appear at the top or directly go to [http://localhost:8000/shifts/](http://localhost:8000/shifts/)

once i got some note from you guys, I'll continue on the shift management. thanks in advance!

**Comment by yeonwoon** [comment]
Regarding delete confirmation, we could just show a page... as it is in [DeleteView example](https://docs.djangoproject.com/en/1.8/ref/class-based-views/generic-editing/#django.views.generic.edit.DeleteView). Modal view would be nicer, but normal view also works. Generally, small modal dialog is not good in terms of UX anyways.

**Comment by jmewes** [comment]
@christophmeissner I am quite sure that PhantomJS can handle the modal view dialogs from Bootstrap. They also look quite good.

**Comment by jmewes** [comment]
@yeonwoon This is how Rian and I imagined the structure of the dialogs: https://gomockingbird.com/projects/fnzc6qu/4gXVnC

**Comment by yeonwoon** [comment]
@jmewes sure thing. I have the mock-up in mind. it was a good starting point indeed. However, now it makes me confusing I'm afraid. I guess by now you caught up on models -- if not, try [graph_models](http://django-extensions.readthedocs.org/en/latest/graph_models.html), or see the attached png below. and please compare them with the mock-up.

I'd like to make sure tech design/spec first at this stage, rather than just finishing up while it's unclear. Also, I would take possible model changes into account -- if it happens anytime soon (need @christophmeissner's help!). Otherwise, we could end up with working twice.

PS. github doesn't seem to support .svg as a attachment.
![vp](https://cloud.githubusercontent.com/assets/471401/10943114/59a2bd1e-8313-11e5-9a5a-a408af4299ff.png)

**Comment by christophmeissner** [comment]
@yeonwoon, @jmewes let me know if and how I can help you with the data model.

**Comment by jmewes** [comment]
@yeonwoon After the submission of the shift creation form, please create new entries in the `organizations_task` table and the `scheduler_shift` table.

The form should contain a drop-down menu for the Facility, name and description for the task. The form should also contain the start/end time(s) and date(s) for the shift. 
@christophmeissner Do we need to declare the "Place" for the new shift? For me it seems like we only need the "Facility" as each Facility has only one Place.

**Comment by jmewes** [comment]
@christophmeissner Can you please explain the steps necessary to create the test data for the Organization Manager manually in the admin interface?

**Comment by jmewes** [comment]
@christophmeissner, @yeonwoon : Please have a look on my first pull request and post review comments (I am used to discussions about implementation details, don't hesitate to question my implementation.) My idea was that we can bring the first part live even though it's not the complete feature (only view/delete shifts). 

https://github.com/coders4help/volunteer_planner/pull/242

@yeonwoon Sorry that it doesn't make your cooperation easier. Here some tips for your own pull request to upstream. I'd continue on your branch to implement the feature. Once my pull request is upstream you can create a completely new branch on make pull can make a new commit on the new branch from the changes on the old branch. I used `git cherry-pick <sha>` and `git checkout <branch> -- <file-path>` for this purpose. Again, sorry for the additional complexity but I'm afraid there is no other way to get this feature done together with remote collaboration.

**Comment by christophmeissner** [comment]
For promoting/creating manager see https://github.com/coders4help/volunteer_planner/wiki/How-to-promote-a-user-as-a-(shift)-manager-for-facilities

**Comment by yeonwoon** [comment]
@jmewes it's gone upstream too early :) I just started working based off of it rather than leaving any comment on the closed pull request.

I created a pull request just moment ago. with those changes, add/edit shift should be working just fine. however, it's still initial version. things are subject to change as we develop.

*here are respective screenshots for your conveniences.
### add shift ###
![add-new](https://cloud.githubusercontent.com/assets/471401/11014978/da7e2510-854b-11e5-9fe8-4f3ee7e310fe.png)
### edit shift ###
![edit](https://cloud.githubusercontent.com/assets/471401/11014979/de051dd8-854b-11e5-880d-c5fb14229a1f.png)

and here's some questions regarding shift management for @christophmeissner and @jmewes 
- what are the usual requests, and how do staffs handle them manually? i'd like to polish the form based on practical usage.
- is there any considerable edge cases with the requests?
- how we handle the Shift.workplace (fk of organizatios.workplace) (see above screenshot), doesn't this even necessary as Jan pointed?
- does the user need to be a manager of the organisation in order to manage shifts? or manager privilege of the facility is enough?
- should user select existing Task in the `add shift form`? or just add new Task instance whenever user creates Shfit. (not sure because what's written on the bullet points at the top of this issue thread)
- we allow user to add multiple shifts from single request, which will also create a task. meaning that a single task instance might be associated with multiple shifts. then, how we do with the `edit shift view`? we only allow user to change its schedule? if user wants to edit task description for example, do we provide another view for it?
- any idea on user-friendly input method for date/time field?
- any plan or working in progress changes regarding Task, Shift models? relational changes between models, possible obsolete fields, for exmaple.
- what's the state or plan for `shift templates`?

**Comment by christophmeissner** [comment]
@yeonwoon @janmewes, please sync your collaboration on either one of your own forks. We can't promise to do interim code reviews for pull requests of work in progress. Thanks, you rock!

**Comment by yeonwoon** [comment]
@christophmeissner, above, Jan said he'd continue on my fork, so I think we have our own fork for collab. I've create a pull request for review from committer actually. can't go no further without it. not necessarily be micro-review, but please take a moment to see if it's fine. (also the questions above) thanks in advance!

**Comment by jmewes** [comment]
(1) Currently, the shifts are reported by email and then entered manually in the Django administration area either from scratch ([click here](http://127.0.0.1:8000/admin/scheduler/shift/add/)) or with templates ([click here](http://127.0.0.1:8000/admin/scheduletemplates/shifttemplate/)). AFAIK the current shift creation process is rather cumbersome. That's why we are creating this new feature. Probably currently nobody really knows what the ideal way for the shift creation is. So let's try to create a very simple version, create a pull request, fix the remarks, get feedback from the actual users and then improve the workflow step by step.
(2) Yes, but we don't know them yet. :smiley: So let's try to create a very simple version ...
(3) I suggest leaving out the workplace from the shift creation form. I guess that the Volunteer can go to the Facility and then make their way to the Workplace. In the admin interface dialogue ([click here](http://127.0.0.1:8000/admin/scheduler/shift/add/)) the Workplace is also not a mandatory field. Looking on the shifts of the live platform it seems to me like the Workplace data base entry is not relevant at the moment.
(4) If the user is a manager of the Facility he should have the rights to manage the Shifts. So he can use our feature if he is a manager of the Facility or the Facility's Organization.
(5) I talked with Chris about this point with in Berlin. He agreed that by now a new Task instance will be created along with the Shift creation. Later on the Task input field can be extended to reuse existing Tasks with auto-completion in the Shift creation dialogue.
(6) Let's let the user edit the Task description along with the Shift. If multiple instances of a task where created its still the same task and I don't see a problem that all other Shifts with the same task will be modified implicitly with the modification of one Shift.
(7) I suggest to use a date picker. I also believe that the dialogue shown in the picture below would provide good usability.
(8) I believe that there will be no major changes in the data model in the near future as it is already pretty mature and there is already a lot of live data which would need to be migrated.
(9) I have not started yet to work on the shift templates. I will put in about an hour today and plan to continue next Saturday afternoon.

>(1)    what are the usual requests, and how do staffs handle them manually? i'd like to polish the form based on practical usage.
>(2)    is there any considerable edge cases with the requests?
>(3)    how we handle the Shift.workplace (fk of organizatios.workplace) (see above screenshot), doesn't this even necessary as Jan pointed?
>(4)    does the user need to be a manager of the organisation in order to manage shifts? or manager privilege of the facility is enough?
>(5)    should user select existing Task in the add shift form? or just add new Task instance whenever user creates Shfit. (not sure because what's written on the bullet points at the top of this issue thread)
>(6)    we allow user to add multiple shifts from single request, which will also create a task. meaning that a single task instance might be associated with multiple shifts. then, how we do with the edit shift view? we only allow user to change its schedule? if user wants to edit task description for example, do we provide another view for it?
>(7)    any idea on user-friendly input method for date/time field?
>(8)    any plan or working in progress changes regarding Task, Shift models? relational changes between models, possible obsolete fields, for exmaple.
>(9)    what's the state or plan for shift templates?

My suggestion for the structure of the shift creation dialogue:
![draft-shift-creation-dialog](https://cloud.githubusercontent.com/assets/5235584/11324824/9317e5b4-913d-11e5-9e1c-dfb8f2ebd238.png)

**Comment by jmewes** [comment]
@christophmeissner,
What do you think about the structure of the shift creation dialogue in screenshot above? Do you agree to leave out the Workplace by now (my rationale is described in answer (3) in the comment above)?

**Comment by jmewes** [comment]
Yeonwoon and I decided to continue our work on this branch on my fork:
https://github.com/jmewes/volunteer_planner/commits/feature/shift_manager_interface
