### ISSUE TITLE
During registration password errors are not displayed

### ISSUE THREAD

**Issue by alper** [coders4help/volunteer_planner#292]
If there are errors with your password (mismatch, empty etc.), these are not displayed during registration.

**Comment by alper** [comment]
Ok, this now throws away all my data again because cleaned_data is empty after validation…

**Comment by klinger** [comment]
alper, is your comment connected to the already merged commit "d326b7d20a6c289f88c9079e04a7ff5b79871af8 @srenatus srenatus commited" 
or to commit 4b44ad8?

**Comment by alper** [comment]
Both? I think the issue is still in there but I would need to test.

The form should render previously entered data but in the new class RegistrationFormUniqueEmail cleaned_data is empty after submitting.

**Comment by Doca** [comment]
is this solved on development branch already?

**Comment by klinger** [comment]
If I enter two different passwords:
"The two password fields didn't match."
and password field 2 is cleared, other fields are filled

If I enter an already used username:
"Username already exists. Please choose a different username. "
and username field is cleared, other fields are filled

If I enter an already used email: 
"This email address is already in use. Please supply a different email address."
and emailfield is cleared, other fields are filled.


Tested on version 3.0.1 - so thats fixed in develop and production system.
Conclusion: No problem anymore.
Issue closed.
