### ISSUE TITLE
Migration from Django version 1.8 to 1.9? 

### ISSUE THREAD

**Issue by klinger** [coders4help/volunteer_planner#335]
Is it possible to migrate from Django 1.8 to Django 1.9 release?

Its probably possible to migrate without much effort.

Is it possible to migrate "out of the box"?
What would have to be done to do the migration?
Is there cause we cannot/should not migrate?

(suggested by @zerok )

**Comment by lwm** [comment]
Well, I had a play around with it. Here is [my branch](https://github.com/lwm/volunteer_planner/commit/d5ead90fae365ceb01006327ce46489e1c1ca29b) so far. 

There was a few necessary package updates, but not much. The tests are failing with the following error:

```
...
self = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x7ff971a93d60>
query = 'SELECT "registration_registrationprofile"."id", "registration_registrationprofile"."user_id", "registration_registrat...ationprofile"."activated" FROM "registration_registrationprofile" ORDER BY "registration_registrationprofile"."id" ASC'
params = ()
OperationalError: no such column: registration_registrationprofile.activated
```

When I run a `py.test --nomigrations`, the tests pass. I think the problem is related to the `registration_history/migrations/0001_squashed_0006_remove_model.py` migration but I am not familiar with the changes.

Any ideas?
