### ISSUE TITLE
Using docker-compose

### ISSUE THREAD

**Issue by asymmetric** [coders4help/volunteer_planner#337]
Hi,

As a non-Python developer, I found the setup instructions quite long and brittle. So I decided to make life easier for myself and setup 2 docker containers (one for the DB, one for django) and wire them up with [docker compose](https://docs.docker.com/compose/).

You can take a look at the [updated README](https://github.com/asymmetric/volunteer_planner/tree/docker-compose#project-setup-for-development), and tell me what you think.

At the moment, there are still some issues with running tests: the database `GRANT`s for user `vp` don't allow it to create other databases, so no `test_volunteer_planner` (by the way, this is a problem in your README too).

If there's any interest in merging this, I'll look for ways to make running the tests work out of the box, and make additional fixes to the README. Otherwise, I'll keep the fork to myself, rebasing on yours while I  work on other features (mostly OSM integration).

Thanks.

**Comment by lwm** [comment]
This would solve #321.

I think Docker is awesome but rather than have it take over as the new way to deploy the project, you could create a `README.docker` and make a small note that the project is also Docker-ized for those who need it.

That's just my two cents, I just found this project and was thinking of doing the same thing. Good job!

**Comment by klinger** [comment]
Thanks. @Merged. See PR #361 . 
Definitely interested in getting the tests running, I would be happy to see a pull request for the documentation.

**Comment by lwm** [comment]
:rocket:
