### ISSUE TITLE
Facebook-Login / Google-Login / ..

### ISSUE THREAD

**Issue by klinger** [coders4help/volunteer_planner#371]
It would be nice to enable third party login providers like Facebook-login.

BUT: Only the login process may be tracked by the the third party. The usage of the site must be possible without connection to the login provider.

How could we achieve this? How large is the effort to do this?

**Comment by asymmetric** [comment]
Is this really a good idea from a privacy perspective? I for one would like this project to take a more "idealistic" stance. But please tell me if I'm completely wrong :)

UX-wise, the signup process seems quite simple to me already, so I don't think there would be that big of a gain in that area either.

**Comment by klinger** [comment]
I share your privacy concerns. I personally have never used any facebook connect on a website. And I am not going to use it.

But:
The "facebook-login" may be important to reduce barriers. There may be a higher chance for some groups of users to use VP if they dont have to create a new login/password pair.

This feature has to be implemented with all privacy features - and the normal login process should be the way it is now.

This feature is tagged "question" because its only a discussion. There is no decision yet.

**Comment by pitpalme** [comment]
I see your points about privacy.
But on the other hand I see usability aspects as well. Some people don't want to create a new login over and over again. They like "pseudo single sign-on" (even if they can't pronounce it).
In my opinion we can go the way to *offer* FB / Google OAuth login, because no-one will be enforced, or even only "encouraged" to use it. Once implemented it should be simply present, maybe even only below the ordinary login and register options. 
Only as an alternative: "If you don't want to create a new login: here it is. Be aware, FB/Google/Whoever will know, you log in here, because we need to ask them for permission to let you enter, but that's it. We will not send any other data to this company."

If this way we can get people to think about helping with low entrance barrier, me personally I'm fine with it :)

Just my 2¢
